[redis]
addr = "localhost:6379"
password = ""
db = 0

[storage]
type = "s3"

[storage.s3]
endpoint = "https://example.com"
region = "us-east-1"
bucket = "nix4loong"
access_key = "YOUR_ACCESS_KEY_HERE"
secret_key = "YOUR_SECRET_KEY_HERE"

[daemon]
log_level = "info"
ssh_command = "ssh user@host 'sudo nixos-rebuild switch'"
ssh_debounce_minutes = 5
ssh_timeout_minutes = 10
enable_ssh_task = false
delete_after_sync = false

[publish]
max_retry = 3
timeout_minutes = 30

[http]
addr = ":8080"

[cache]
max_concurrent_s3_checks = 10
allowed_prefixes = ["store/", "nix/"]